### ISSUE TITLE
Chrooted environment

### ISSUE THREAD

**Issue by psztoch** [oskar456/dzonegit#12]
Please add new config entry, in example: dzonegit.configcheckoutpath
Default value is get from dzonegit.checkoutpath.
But if you want, you can put name for chrooted environment.
dzonegit.configcheckoutpath is used only in config json.

Example for RHEL 8 default chrooted named environnemnt:
dzonegit.checkoutpath=/var/named/chroot/var/named/data
dzonegit.configcheckoutpath=/var/named/data

You can add new macros for json template, too:
$localzonefile with path relative to root of git repository.

"item": "zone \"$zonename\" {\n type master;\n file \"/var/named/data/$localzonefile\";\n};"

**Comment by oskar456** [comment]
Fixed in #14
