### ISSUE TITLE
Travis CI is not updated, integration is disabled

### ISSUE THREAD

**Issue by HalisCz** [oskar456/dzonegit#6]
### Issue

- `.travis.yml` seems to be outdated (Python 3.7 is missing)
- Travis CI integration is not enabled (according to https://travis-ci.com/oskar456/dzonegit)

### Proposed solutions:
- option: update
  - update `.travis.yml`
  - enable Travis CI integration
- option: deprecate
  - remove `.travis.yml` file

**Comment by oskar456** [comment]
Thank you. You got me completely confused. The thing is, this is integrated with Travis-CI.org (the free thing for open-source), not Travis-CI.com (which used to be payed only). Now they are somehow unifying it into travis-ci.com, but until then, I'll happily continue with the .org version.
